[project]
name = "cahier-de-vacances"
version = "0.1.0"
description = "2026"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.9",
    "matplotlib>=3.11.0",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
    "pypdf>=6.16.2",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=6.0.1",
    "torch>=2.13.0",
    "transformers>=5.16.1",
]
